/*  입양 간 동물 중 보호 기간 가장 길었던 동물 두 마리 조회하기 
	DATEDIFF 사용하면 날짜 차이 구할 수 있음 */
SELECT	O.ANIMAL_ID, O.NAME
FROM	ANIMAL_INS AS I JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT	2;